/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package co.edu.unicolombo.pb.Gastos.vistas;

import co.edu.unicolombo.pb.Gastos.Cliente;
import co.edu.unicolombo.pb.persistencia.Almacenamiento;
import java.io.IOException;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class VentanaClientes extends javax.swing.JDialog {

    /**
     * Creates new form VentanaClientes
     */
    public VentanaClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CampoNrodocumento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CampoName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CampoCel = new javax.swing.JTextField();
        campoApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonGuardar = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();
        ButtonBuscar = new javax.swing.JButton();
        ButtonEliminar = new javax.swing.JButton();
        ButtonEditar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion Cliente");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULARIO PARA GESTIONAR CLIENTE");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 2, true), "Datos de Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(0, 102, 204))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Cedula");

        CampoNrodocumento.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        CampoNrodocumento.setMinimumSize(new java.awt.Dimension(60, 40));
        CampoNrodocumento.setPreferredSize(new java.awt.Dimension(65, 45));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nombre");

        CampoName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        CampoName.setMinimumSize(new java.awt.Dimension(60, 40));
        CampoName.setPreferredSize(new java.awt.Dimension(65, 45));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Telefono");

        CampoCel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        CampoCel.setMinimumSize(new java.awt.Dimension(60, 40));
        CampoCel.setPreferredSize(new java.awt.Dimension(65, 45));

        campoApellido.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        campoApellido.setMinimumSize(new java.awt.Dimension(60, 40));
        campoApellido.setPreferredSize(new java.awt.Dimension(65, 45));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText(" Apellido");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoNrodocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampoCel, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addComponent(CampoName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(CampoNrodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CampoName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CampoCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/pb/Gastos/vistas/iconos/Cliente228px.png"))); // NOI18N

        ButtonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/pb/Gastos/vistas/iconos/Guardar48px.png"))); // NOI18N
        ButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarActionPerformed(evt);
            }
        });

        ButtonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/pb/Gastos/vistas/iconos/Cancelar48px.png"))); // NOI18N
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        ButtonBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/pb/Gastos/vistas/iconos/Search48px.png"))); // NOI18N
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        ButtonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/pb/Gastos/vistas/iconos/Eliminar24px.png"))); // NOI18N
        ButtonEliminar.setEnabled(false);
        ButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarActionPerformed(evt);
            }
        });

        ButtonEditar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ButtonEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/pb/Gastos/vistas/iconos/Editar24px.png"))); // NOI18N
        ButtonEditar1.setEnabled(false);
        ButtonEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(226, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonCancelar)
                                .addGap(45, 45, 45)
                                .addComponent(ButtonEliminar)
                                .addGap(35, 35, 35)
                                .addComponent(ButtonEditar1)
                                .addGap(28, 28, 28)
                                .addComponent(ButtonBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonGuardar)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonCancelar)
                    .addComponent(ButtonGuardar)
                    .addComponent(ButtonBuscar)
                    .addComponent(ButtonEliminar)
                    .addComponent(ButtonEditar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarActionPerformed
        String cedula = CampoNrodocumento.getText();
        String nombre = CampoName.getText();
        String apellido = campoApellido.getText();
        String celular = CampoCel.getText();
        if (Cliente.ClientesBD.containsKey(cedula)) {
            JOptionPane.showMessageDialog(this, "El cliente con cedula: " + cedula + " ya esta registrado");
            return;
        }
        Cliente c = new Cliente();
        c.nroDocumento = cedula;
        c.nombre = nombre;
        c.apellido = apellido;
        c.celular = celular;
        Cliente.ClientesBD.put(cedula, c);

        try {
            Almacenamiento.guardar(Cliente.ClientesBD);
            JOptionPane.showMessageDialog(this, "Cliente registrado con exito!!");
            LimpiarCampos();
        } catch (IOException error) {
            JOptionPane.showMessageDialog(this, error.getMessage());
        }

    }//GEN-LAST:event_ButtonGuardarActionPerformed
    public void LimpiarCampos() {
        CampoNrodocumento.setText("");

        CampoName.setText("");
        campoApellido.setText("");
        CampoCel.setText("");
        ButtonEditar1.setEnabled(false);
        ButtonEliminar.setEnabled(false);
    }

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        try {
            String cedula = JOptionPane.showInputDialog("Ingrese el numero de documento para buscar");

            Cliente.ClientesBD = Almacenamiento.recuperar();
            if (Cliente.ClientesBD.containsKey(cedula)) {
                Cliente c = Cliente.ClientesBD.get(cedula);
                CampoNrodocumento.setText(cedula);
                CampoName.setText(c.nombre);
                campoApellido.setText(c.apellido);
                CampoCel.setText(c.celular);

            } else {
                JOptionPane.showMessageDialog(this, "El cliente no existe");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void ButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformed

    }//GEN-LAST:event_ButtonEliminarActionPerformed

    private void ButtonEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditar1ActionPerformed
        if (CampoNrodocumento.getText() == null || CampoNrodocumento.getText().isEmpty()) {
            String msj = " Busca primero un cliente ";
            JOptionPane.showMessageDialog(this, msj);
            LimpiarCampos();
            return;

        }
        if (CampoNrodocumento.getText().equals(Cliente.ClientesBD) != true) {
            String msj = " La cedula no coincide con la cedula del Cliente consultado ";
            JOptionPane.showMessageDialog(this, msj);
            LimpiarCampos();
            return;

        }
        Cliente c = Cliente.ClientesBD.get(CampoNrodocumento.getText());
        String cedula = CampoNrodocumento.getText();

        String nombre = CampoName.getText();
        String correo = campoApellido.getText();
        String Celular = CampoCel.getText();

        c.nombre = nombre;
        c.celular = Celular;
        Cliente.ClientesBD.put(c.nroDocumento, c);
        String msj = " Cliente modificado con exito ";
        JOptionPane.showMessageDialog(this, msj);
        LimpiarCampos();
    }
        
        public void LimpiarCampos1(){
         CampoNrodocumento.setText("");
        CampoName.setText("");
        campoApellido.setText("");
        CampoCel.setText("");
        ButtonEditar1.setEnabled(false);
        ButtonEliminar.setEnabled(false);
    }//GEN-LAST:event_ButtonEditar1ActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, " Desea cerrar el formulario? ",
                "ALERTA - CONFIRMAR ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaClientes dialog = new VentanaClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonEditar1;
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JTextField CampoCel;
    private javax.swing.JTextField CampoName;
    private javax.swing.JTextField CampoNrodocumento;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
